core: set lifc_family to AF_UNSPEC correctly
to fix the following build failure on illumos-based systems:
```
iface-pfroute.c: In function 'avahi_interface_monitor_sync':
iface-pfroute.c:523:22: error: assignment to 'sa_family_t' {aka 'short unsigned int'}
 from 'void *' makes integer from pointer without a cast [-Wint-conversion]
523 |     lifc.lifc_family = NULL;
    |                      ^
```
The lifn_family field is set to AF_UNSPEC above to count both AF_INET
and AF_INET6 interfaces so the lifc_family field should be set to
AF_UNSPEC as well to retrive those interfaces. In practice AF_UNSPEC is
0 so it kind of worked with NULL as well.

It already popped up downstream and was somewhat addressed by
casting NULL to sa_family_t explicitly in
https://github.com/NetBSD/pkgsrc/commit/e6a3c3e4ea4da2ff5e4640c9c435e155ad7c13ad.
and turning it into a non-fatal pointer-to-int-cast warning.

See also https://man.omnios.org/man7p/if