core: refuse to create wide-area record browsers when wide-area is off
It fixes a bug where it was possible for unprivileged local users to
crash avahi-daemon (with wide-area disabled) by creating record browsers
with the AVAHI_LOOKUP_USE_WIDE_AREA flag set via D-Bus (either by calling
the RecordBrowserNew method directly or by creating hostname/address/service
resolvers/browsers that create those browsers internally themselves).

```
$ gdbus call --system --dest org.freedesktop.Avahi --object-path / --method org.freedesktop.Avahi.Server.ResolveHostName -- -1 -1 yo.local -1 1
Error: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```
```
dbus-protocol.c: interface=org.freedesktop.Avahi.Server, path=/, member=ResolveHostName
avahi-daemon: wide-area.c:725: avahi_wide_area_scan_cache: Assertion `e' failed.
==307948==
==307948== Process terminating with default action of signal 6 (SIGABRT)
==307948==    at 0x4B3630C: __pthread_kill_implementation (pthread_kill.c:44)
==307948==    by 0x4ADF921: raise (raise.c:26)
==307948==    by 0x4AC74AB: abort (abort.c:77)
==307948==    by 0x4AC741F: __assert_fail_base.cold (assert.c:118)
==307948==    by 0x48D8B85: avahi_wide_area_scan_cache (wide-area.c:725)
==307948==    by 0x48C8953: lookup_scan_cache (browse.c:351)
==307948==    by 0x48C8B1B: lookup_go (browse.c:386)
==307948==    by 0x48C9148: defer_callback (browse.c:516)
==307948==    by 0x48AEA0E: expiration_event (timeeventq.c:94)
==307948==    by 0x489D3AE: timeout_callback (simple-watch.c:447)
==307948==    by 0x489D787: avahi_simple_poll_dispatch (simple-watch.c:563)
==307948==    by 0x489D91E: avahi_simple_poll_iterate (simple-watch.c:605)
==307948==
```

wide-area has been disabled by default since
9c4214146738146e454f098264690e8e884c39bd (v0.9-rc2).

https://github.com/avahi/avahi/security/advisories/GHSA-mhf3-865v-g5rc