ci: switch to Ubuntu 24.04 (#606)
* ci: switch the build workflow to Ubuntu 24.04

* ci: make the sed command work with DEB822 source format

Fixes:
```
+ apt-get build-dep -y avahi
Reading package lists...
E: You must put some 'deb-src' URIs in your sources.list
Error: Process completed with exit code 100.
```

* ci: install mono stuff explicitly

Fixes:
```
configure: error: Can not find "mcs" - The Mono C-Sharp Compiler) in your PATH
```
and
```
configure: error: Package requirements (monodoc >= 1.1.8) were not met:
```
and
```
error CS0006: Metadata file `Mono.Posix' could not be found
```

* ci: bump super-linter and point it to Ubuntu 24.04 explicitly

to make it recognize the ubuntu-24.04 label and prevent it from getting
updated (and potentially breaking automatically)

Fixes:
```
.github/workflows/build.yml:17:14: label "ubuntu-24.04" is unknown
...
     |
  17 |     runs-on: ubuntu-24.04
     |              ^~~~~~~~~~~~
  ------
```

* ci: switch CodeQL to Ubuntu 24.04

* ci: point shellcheck to Ubuntu 24.04 explicitly

to make it consistent with the other actions and prevent it from getting
updated (and potentially breaking) automatically.

* ci: pass -fno-sanitize=function explicitly

to get around https://github.com/avahi/avahi/issues/584

* ci: switch coverage to Ubuntu 24.04

and ignore "source" warnings when capturing coverage

Fixes:
```
geninfo: ERROR: unable to open /home/runner/work/avahi/avahi/conftest.c: No such file or directory
```

* ci: keep ubuntu-22.04 in the CIFuzz action

It can't be bumped to Ubuntu 24.04 due to
https://github.com/google/oss-fuzz/issues/12042.

* ci: switch coverity to Ubuntu 24.04