Use external gettext instead the glib one
gettextize is called without `--intl` option, so AM_GNU_GETTEXT([external])
should be used instead of AM_GNU_GETTEXT for triggering internationalization
support [1].

Furthermore, building avahi fails for build system without glib:
  error: possibly undefined macro:
         AM_GLIB_GNU_GETTEXT

Using AM_GNU_GETTEXT([external]) allows us to build avahi on systems providing
an external gettext library.

[1] http://www.elpro.pl/dokumentacje/596-gettext13